#!/bin/bash

# The testing model : Shu1d or Cosine
MODEL=Shu1d
# Pseudo / Quasi
RandomMode=Quasi

# generating model
rm -rf model
if [ $MODEL == 'Shu1d' ]; then
  sparx run task_shu1d \
  out=model \
  abundance=1e-9
elif [ $MODEL == 'Cosine' ]; then
  sparx run task_cosine1d \
  out=model \
  abundance=1e-8
fi

if [ $RandomMode == 'Pseudo' ];then
  QMC='qmc=False'
  Nrun=10
  REQUEST_SNR=(10 15 20 30 40 50 60 80 100)
elif [ $RandomMode == 'Quasi' ];then
  QMC='qmc=True'
  Nrun=1
  REQUEST_SNR=(10 15 20 30 40 50 60 80 100 200 400 800)
fi



NSNR=${#REQUEST_SNR[@]}
FILENAME=$MODEL$RandomMode

for j in `seq $Nrun`
do
  
  output=$FILENAME'_'$j
  
  DAT=$FILENAME'RAYS_'$j'.dat'
  rm -f $DAT

  for i in `seq 0 $((NSNR-1))`
  do
    SNR=${REQUEST_SNR[$i]}
    case=$output'_snr_'$SNR
    # take previous snr run as initial condition
    if [ $i != 0 ]; then 
      POPS='pops='$output'_snr_'${REQUEST_SNR[$((i-1))]} 
    else
      POPS=''
    fi
    # run AMC
    rm -f $case
    
    sparx run task_amc \
    source=model \
    $POPS \
    out=$case \
    molec='hco+' \
    snr=$SNR \
    nrays=50 \
    raniter=1 \
    fixiter=1 \
    $QMC \
    | tee $case.log
    
    # grep numer of rays using in this case
    RAYS=`grep 'rays' $case.log | grep -v 'Iterating for convergence' | tail -n 1 | sed -e 's/rays//g' -e 's/.*->//g'`
    echo $SNR $RAYS | tee -a $ $DAT 
  done
done