#!/bin/bash

rm -rf coldens/ coldens.fits

printf "${LIGHTCYAN}START THE MAPPING OF COLUMN DENSITY ${NC}\n"

sparx run task_coldens \
source=model \
out=coldens 
# subres="[['-10asec','-10asec','10asec','10asec',4]]"

