#!/bin/bash
###### Job name ######
#PBS -N SPARX
###### Output files ######
#PBS -e SPARX.err
#PBS -o SPARX.log
###### Queue name #######
#PBS -q large
###### Number of nodes and cores ######
#PBS -l nodes=8:ppn=12
###### Sends mail to yourself when the job begins and ends ######
#PBS -M ithsieh@asiaa.sinica.edu.tw
#PBS -m be
###### Specific the shell types ######
#PBS -S /bin/bash

PBS_O_WORKDIR=~/test

###### Enter this job's working directory ######
mkdir -p $PBS_O_WORKDIR
cd $PBS_O_WORKDIR

###### Load modules to setup environment ######
source ~/.load_sparx_module


###### Run parallel jobs ######
rm -rf pops* history.log 

awk '!x[$0]++' $PBS_NODEFILE > LAMHOST
$LAM_HOME/bin/lamboot LAMHOST
HOSTNAME=`hostname`
CLUSTERNAME=${HOSTNAME:0:2}
sparx_version=`which sparx-dev$CLUSTERNAME`

$LAM_HOME/bin/mpiexec C \
$sparx_version --parallel run task_amc \
source=model \
out=pops \
molec='co_21lev' \
trace='True' \
lte='True' \
tolerance=5e-3 \
snr=20 \
minpop=1e-6 \
nrays=1000 \
maxiter=20 \
raniter=2 \
fixiter=2 \
| tee history.log

$LAM_HOME/bin/lamhalt
rm -rf LAMHOST
