#!/bin/bash


# Convenience function for setting up apps
setup_app() {
    home_dir=$1
    export C_INCLUDE_PATH=${home_dir}/include:${C_INCLUDE_PATH}
    export PATH=${home_dir}/bin:${PATH}
    export LIBRARY_PATH=${home_dir}/lib:${LIBRARY_PATH}
    export LD_LIBRARY_PATH=${home_dir}/lib:${LD_LIBRARY_PATH}
    export MANPATH=${home_dir}/man:${MANPATH}
}

# OPENMPI
setup_app $HOME/opt/openmpi-2.0.0

# FITSIO
setup_app $HOME/opt/cfitsio

# HDF5
setup_app $HOME/opt/hdf5-1.8.17








