#!/bin/bash

rm -rf model

# generating Shu's 1D model
# printf "${LIGHTBLUE}GENERATING SPH1D GRID : SHU's MODEL${NC}\n"
# sparx run task_shu1d out=model abundance=1e-9

# generating AGB 1D model
printf "${LIGHTBLUE}GENERATING SPH1D GRID : Shu Model\n"
#sparx run task_agb1d out=model 

\cp ../../preprocessor/presparx/Shu1D/* ./
presparx -o model