#!/bin/bash


rm -rf map/ tau/ map.fits tau.fits vis.vtk

printf "${LIGHTCYAN}START THE MAPPING OF LINE EMISSION ${NC}\n"

sparx run task_lineobs \
source=../storage/cyl2d_model/model_env_disk \
lte='True' \
molec='hco+' \
out=map \
line=1 \
npix="[128,128]" \
chan="[64,'0.2kms^-1']" \
rotate="['0deg', '30deg', '0deg']" \
subres="[['-10asec','-10asec','10asec','10asec',1]]"