#!/bin/bash

rm -rf pops pops*
# generating non-LTE level population
printf "${YELLOW}RUNNING AMC${NC}\n"

sparx run task_amc \
source=model \
out=pops \
trace='True'

# Generating CH3CN pops for overlap-emission test
#$sparx_version run task_amc \
#source=model \
#out=pops \
#molec=ch3cn \
#trace='True'


# restore the population 
#mkdir -p ../storage/1Dpops/
#cp pops ../storage/1Dpops/pops