#!/bin/bash

rm -rf pops
# generating non-LTE level population
printf "${YELLOW}RUNNING AMC${NC}\n"

sparx run task_amc source=model out=pops molec=hco+

# Generating CH3CN pops for overlap-emission test
#$sparx_version run task_amc \
#source=model \
#out=pops \
#molec=ch3cn \
#trace='True'