#!/bin/bash


# Initial condition : hot / cold
INITIAL=hot
# ABUNDANCE
ABD_ARRAY=(1E-3 1E-4 1E-5 1E-6 1E-7 1E-8 1E-9)
SNR_ARRAY=(20 40 60 80 100 200 400 1000 2000)
#ABD_ARRAY=(1E-7)
#SNR_ARRAY=(20)

if [ $INITIAL == 'hot' ]; then
  LTE='lte=True'
elif [ $INITIAL == 'cold' ]; then
  LTE='lte=False'
fi


NABD=${#ABD_ARRAY[@]}
NSNR=${#SNR_ARRAY[@]}
for i in `seq 0 $((NABD-1))`
do
  ABD=${ABD_ARRAY[$i]}
  
  rm -f model
  sparx run task_shu1d \
  out=model \
  abundance=$ABD
  
  for j in `seq 0 $((NSNR-1))`
  do
    
    SNR=${SNR_ARRAY[$j]}
    OUT=$INITIAL'_'$ABD'_'$SNR
    
    rm -f $OUT
    sparx run task_amc \
    source=model \
    out=$OUT \
    molec='hco+' \
    snr=$SNR \
    $LTE \
    nrays=256 \
    raniter=1 \
    fixiter=1 \
    sor=1.0 \
    ali='True' \
    dat='True' \
    | tee $OUT.log
    
  done
done