#!/bin/bash

rm -rf map/ tau/ map.fits tau.fits

printf "${LIGHTCYAN}START THE MAPPING OF ZEEMAN EFFECT (STOKES V) ${NC}\n"

sparx run task_zeeman \
source=../storage/1Dpops/pops \
out=map \
line=1 \
tau=tau \
npix="[2,2]" \
subres="[['-10asec','-10asec','10asec','10asec',4]]"
