#!/bin/bash
###### Job name ######
#PBS -N SPARX
###### Output files ######
#PBS -o SPARX.out
#PBS -e SPARX.err
###### Number of nodes and cores ######
#PBS -l nodes=20:ppn=16
###### Queue name ######
#PBS -q large
###### Specific the shell types ######
#PBS -S /bin/bash

###### Enter this job's working directory ######

PBS_O_WORKDIR=/tiara/home/ithsieh/sparx-alpha/unit_tests/tmp
mkdir -p $PBS_O_WORKDIR
cd $PBS_O_WORKDIR

###### Load modules to setup environment ######
source ~/.load_sparx_module


rm -rf pops* history.log 

if [ -n "$PBS_NODEFILE" ]; then
  if [ -f $PBS_NODEFILE ]; then
    awk '!x[$0]++' $PBS_NODEFILE > MPIHOST
    NPROCS=`wc -l < MPIHOST`
    sed -e 's/$/ slots=1/' -i MPIHOST
  fi
fi



$OPENMPI_HOME/bin/mpirun -v -machinefile MPIHOST -np $NPROCS \
sparx-xl --parallel run task_amc \
source=model \
pops=storage_pops \
out=pops \
trace='True' \
lte='True' \
nrays=100 \
raniter=1 \
fixiter=1 | tee history.log

rm -rf MPIHOST


