#!/bin/bash

rm -rf map/ tau/ map.fits tau.fits

printf "${LIGHTCYAN}START THE MAPPING OF LINE EMISSION ${NC}\n"

sparx run task_lineobs \
source=../storage/1Dpops/pops \
out=map \
line=1 \
tau=tau \
npix="[31,31]" \
chan="[31,'0.1kms^-1']" 
