#!/bin/bash

rm -rf map/ tau/ map.fits tau.fits

printf "${LIGHTCYAN}START THE MAPPING OF LINE EMISSION ${NC}\n"

sparx run task_lineobs \
source=pops \
out=map \
line=1 \
tau=tau \
npix="[31,31]" \
chan="[31,'0.1kms^-1']" \
subres="[['-10asec','-10asec','10asec','10asec',4]]"
