#!/bin/bash

rm -rf map/ stokesQ_map/ stokesU_map/ tau/ map.fits tau.fits

printf "${LIGHTCYAN}START THE MAPPING OF CONTINUUM EMISSION ${NC}\n"

sparx run task_contobs \
source=model \
out=map \
wavelen='850um' \
tau=tau \
subres="[['-10asec','-10asec','10asec','10asec',4]]" \
dist='200pc'

