#!/bin/bash

rm -rf map/ stokesq_map/ stokesu_map/ tau/ map.fits tau.fits

printf "${LIGHTCYAN}START THE MAPPING OF CONTINUUM EMISSION ${NC}\n"

$sparx_version run task_contobs \
source=pops \
out=map \
wavelen='850um' \
tau=tau \
subres="[['-10asec','-10asec','10asec','10asec',4]]" 

