#!/bin/bash

rm -rf linectb.vtk 

printf "${LIGHTCYAN}START THE MAPPING OF LINE EMISSION ${NC}\n"

sparx run task_linectb \
source=model \
out=linectb \
lte='True' \
line=1 \
chan="[32,'0.1kms^-1']" \
slice='True'
