#!/bin/bash

rm -rf map/ tau/ map.fits tau.fits

printf "${LIGHTCYAN}START THE MAPPING OF LINE-LTE EMISSION ${NC}\n"

sparx run task_lineobs \
source=model \
out=map \
lte='True' \
line=1 \
tau=tau \
chan="[64, '0.1kms^-1']" \
dist='100pc'
#subres="[['-10asec','-10asec','10asec','10asec',4]]"
