#!/bin/bash

rm -rf map/ tau/ map.fits tau.fits

printf "${LIGHTCYAN}START THE MAPPING OF LINE-LTE EMISSION ${NC}\n"

sparx run task_lineobs \
source=model \
out=map \
lte='True' \
line=1 \
tau=tau \
dist='100pc' \
chan="[128, '0.2kms^-1']"
#subres="[['-10asec','-10asec','10asec','10asec',4]]"
